<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $block \Amasty\GiftCard\Block\Checkout\Cart\GiftCard */ ?>
<?php if ($block->isEnableGiftFormInCart()): ?>
<div class="amgiftcard-apply-code cart-discount">
    <div class="block discount" id="amgiftcard-block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-discount-heading"
                    role="heading"
                    aria-level="2"><?= $block->escapeHtml(__('Apply Gift Card Code')) ?>
            </strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-discount-heading">
            <div data-amgiftcard-js="amgiftcard-info"></div>
            <form id="amgiftcard-form-post" method="post" data-amgiftcard-js="amgiftcard-form-post">
                <?php $getAppliedCodes = $block->getAppliedCodes(); ?>
                <?php if (count($getAppliedCodes)) : ?>
                    <div class="amgiftcard-codes-list">
                        <?php foreach ($getAppliedCodes as $code) : ?>
                            <div>
                                <?= $code->getCode();?>
                                <a class="btn-remove btn-remove-amgiftcard"
                                   href="javascript:void(0);"
                                   data-href="<?= $block->getUrl(
                                       'amgiftcard/cart/remove',
                                       [
                                           'code_id' => $code->getCodeId()
                                       ]
                                   )?>"
                                   title="Remove"
                                   data-amgiftcard-js="amgiftcard-remove"
                                >
                                    <?= $block->escapeHtml(__('Remove')); ?>
                                </a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif;?>
            </form>

            <form id="amgiftcard-form"
                  class="amgiftcard-form"
                  action="<?= $block->getUrl('amgiftcard/cart/apply') ?>"
                  method="post"
                  data-amgiftcard-js="amgiftcard-form"
                  data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-amgiftcard",
                                               "applyButtonGift": "button.action.apply"}}'>
                <div class="fieldset">
                    <input type="hidden" name="remove" id="remove-amgiftcard" value="0" />
                    <div class="field">
                        <label for="coupon_code" class="label"><?= $block->escapeHtml(__('Enter gift card code')) ?></label>
                        <div class="control">
                            <input class="input-text required-entry"
                                   type="text"
                                   id="am_giftcard_code"
                                   name="am_giftcard_code"
                                   value=""
                                   placeholder="<?= $block->escapeHtml(__('Enter gift card code'));?>"
                                   data-validate="{required:true}"
                            />
                        </div>
                    </div>
                </div>
                <div class="amactions-toolbar">
                    <button class="action primary" type="submit" value="<?= $block->escapeHtml(__('Add Gift Card')) ?>">
                        <?= $block->escapeHtml(__('Add Gift Card')) ?>
                    </button>
                    <button type="button"
                            class="action primary"
                            value="<?= $block->escapeHtml(__('Check Gift Card status')) ?>"
                            data-amgiftcard-js="amgiftcard-check-status">
                        <?= $block->escapeHtml(__('Check Gift Card status')) ?>
                    </button>

                </div>

                <script>
                    require([
                        'jquery',
                        'Amasty_GiftCard/js/cart/main'
                    ], function ($) {
                        $('[data-amgiftcard-js="amgiftcard-check-status"]').amGiftcardCart({
                            checkCardUrl: "<?= $block->escapeUrl($block->getUrl('amgiftcard/cart/check')) ?>"
                        });
                    });
                </script>
            </form>
        </div>
    </div>
</div>
<div class="amgiftcard-clear"></div>
<?php endif;?>