<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $order = $block->getOrder() ?>
<?php $dataHelper = $this->helper('MageArray\StorePickup\Helper\Data')?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Order Information') ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($order->getShippingAddress()); ?></address>
            </div>
        </div>

        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
            <?php if ($order->getShippingDescription()): ?>
                <?php echo $block->escapeHtml($order->getShippingDescription()) ?>
            <?php else: ?>
                <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
            <?php endif; ?>
            </div>
			<?php if($dataHelper->isEnabled() == 1):?>
				<?php if ($order->getShippingMethod(true)->getCarrierCode() == "storepickup") :?>
					<?php if($dataHelper->disablePickupDate() != 1):?>
						<?php $dateInfo = "";?>
						<?php if( strtotime($order->getPickupDate()) < 0 || strtotime($order->getPickupDate()) === false):?>
							<?php $dateInfo = "Pickup Date is not selected";?>
						<?php else: ?>	
							<?php $dateInfo = date("Y-m-d", strtotime($order->getPickupDate()));?>
						<?php endif; ?>	
						<div>
							<span><?php echo __("Pickup Date:")?></span>
							<span>
								<?php echo $dateInfo;?>
							</span>
						</div>
					<?php endif; ?>
					<div>
						<span><?php echo __("Working Hours:")?></span>
						<span>
							<?php echo $dataHelper->getWorkingHour($order->getPickupStore());?>
						</span>
					</div>
					<?php $timeInfo = "";?>
						<?php if(empty($order->getPickupTime())):?>
							<?php $timeInfo = "Pickup time is not selected";?>
						<?php else: ?>	
							<?php $timeInfo = $order->getPickupTime();?>
						<?php endif; ?>	
						<div>
							<span><?php echo __("Pickup Time:")?></span>
							<span>
								<?php echo $timeInfo;?>
							</span>
						</div>
				<?php endif; ?>
			<?php endif; ?>
        </div>
    <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($order->getBillingAddress()); ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?php echo $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
