<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php
$_formElement = $this->getFormElement();
$_image = $_formElement->getImage();
?>

<?php if($_imageUrl = $_image->getImageUrl()):?>
    <div id="parent_block" style="position: relative">
        <div id="code_block" style="border: 1px solid #000; cursor: move; position: absolute;background-color:white;width: 100px; text-align: center; font-size: 18px;"><?= $block->escapeHtml(__('Drag me'));?></div>
        <img src="<?php echo $_imageUrl?>" />
    </div>
<?php endif;?>

<script>
    require([
        "jquery",
    ], function($) {
        $(window).load(function () {
            var img_coof = $("#amasty_giftcard_general img")[0];
            var k_height = img_coof.naturalHeight / img_coof.height;
            var k_width = img_coof.naturalWidth / img_coof.width;

            var dragCodeBlock = $('#code_block');
            var fieldX = $('#amasty_giftcard_code_pos_x')[0];
            var fieldY = $('#amasty_giftcard_code_pos_y')[0];

            dragCodeBlock.css('top', parseInt(fieldY.value/k_height) + 'px');
            dragCodeBlock.css('left', parseInt(fieldX.value/k_height) + 'px');

            $(dragCodeBlock).draggable({
                containment:"#parent_block",
                scroll:false,
                stop: function(event, ui) {
                    fieldX.value = ui.position.left*k_width;
                    fieldY.value = ui.position.top*k_height;
                }
            });
        })
    })
</script>