<?php if ($block->hasMethods()) : ?>
    <?php if($this->isCapturingInvoice()): ?>
    <form id="edit_form" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <button type="submit" style="display: none;" id="edit_submit" class="submit-button">submit</button>
    <?php endif; ?>
    <div id="order-billing_method_form">
        <dl class="admin__payment-methods">
            <?php
                $_methods = $block->getMethods();
                $_methodsCount = count($_methods);
                $_counter = 0;
                $currentSelectedMethod = $block->getSelectedMethodCode();
            ?>
            <?php foreach ($_methods as $_method) :
                $_code = $_method->getCode();
                $_counter++;
            ?>
                <dt class="admin__field-option">
                    <?php if ($_methodsCount > 1) : ?>
                        <input id="p_method_<?= $block->escapeHtml($_code); ?>"
                               value="<?= $block->escapeHtml($_code); ?>"
                               type="radio" name="payment[method]"
                               title="<?= $block->escapeHtml($_method->getTitle()); ?>"
                               onclick="payment.switchMethod('<?= $block->escapeHtml($_code); ?>')"
                            <?php if ($block->getSelectedMethodCode() == $_code) : ?>
                                checked="checked"
                            <?php endif; ?>
                            <?php $className = ($_counter == $_methodsCount) ? ' validate-one-required-by-name' : ''; ?>
                               class="admin__control-radio<?= $block->escapeHtml($className); ?>"/>
                    <?php else : ?>
                        <span class="no-display">
                            <input id="p_method_<?= $block->escapeHtml($_code); ?>"
                                   value="<?= $block->escapeHtml($_code); ?>"
                                   type="radio"
                                   name="payment[method]" class="admin__control-radio"
                                   checked="checked"/>
                        </span>
                    <?php endif; ?>

                    <label class="admin__field-label" for="p_method_<?= $block->escapeHtml($_code); ?>">
                        <?= $block->escapeHtml($_method->getTitle()) ?>
                    </label>
                </dt>
                <dd class="admin__payment-method-wrapper">
                    <?= /* @noEscape */ $block->getChildHtml('payment.method.' . $_code) ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php if($this->isCapturingInvoice()): ?>
    </form>
    <?php endif; ?>
    <script>
        require([
            'jquery'
        ], function($){
            $(document).ready(function(){
                $('[name="invoice[capture_case]"]').on('change', function(event){
                    if($(event.currentTarget).val() == 'not_capture'){
                        $('#order-billing_method_form').prev('.admin__page-section-title').css('display', 'none');
                        $('#order-billing_method_form').css('display', 'none');
                    } else {
                        $('#order-billing_method_form').prev('.admin__page-section-title').css('display', 'block');
                        $('#order-billing_method_form').css('display', 'block');
                    }
                });
                <?php if($this->isCapturingInvoice()): ?>
                $('#edit_form').attr('action', $('.capture-post').attr('title'));
                $('.capture-post').on('click', function(event){
                    console.log($('.admin__payment-methods input:checked').val());
                    $('#edit_form').find('.submit-button').trigger('click');
                });
                <?php endif; ?>
            });
        });
    </script>
    <script>
        require([
            'mage/apply/main',
            'Webfitters_Checkout/invoice/create/form'
        ], function(mage) {
            mage.apply();
        <?php if ($_methodsCount != 1) : ?>
            //order.setPaymentMethod('<?= $block->escapeHtml($currentSelectedMethod); ?>');
        <?php else : ?>
            //payment.switchMethod('<?= $block->escapeHtml($currentSelectedMethod); ?>');
        <?php endif; ?>
        });
    </script>
<?php else : ?>
    <div class="admin__message-empty"><?= $block->escapeHtml(__('No Payment Methods')); ?></div>
<?php endif; ?>