<div class="admin__page-section-title">
    <span class="title">Order Credit</span>
</div>
<div class="admin__field field field-order-credit">
	<div class="admin__field-control control" style="display: flex;">
		<input id="order-order-credit" name="order[order_credit]" value="<?php echo $this->getOrderCredit(); ?>" class="input-text admin__control-text" type="text">  
		<button class="action-secondary action-apply" type="button" id="apply_credit"><span>Apply</span></button>                          
	</div>
</div>
<script type="text/javascript">
	requirejs(['jquery', 'Magento_Sales/order/create/form'], function($){
		order.updateOrderCredit = function(){
			var data = this.serializeData('edit_form');
			data._object = {};
			data._object.json = true;
			data._object['order[order_credit]'] = $('#order-order-credit').val();
			this.loadArea(['billing_method', 'totals'], true, data);
		};
		$('#apply_credit').on('click', function(event){
			order.updateOrderCredit();
		});
	});
</script>