<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$product = \Magento\Framework\App\ObjectManager::getInstance()->create('Magento\Catalog\Model\ProductFactory')->create()->load($_item->getProductId());
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <?php 
    $weightlb = (floatval($_item->getQtyWeight()) > 0)?'$'.number_format($_item->getOrderItem()->getRowTotal() / $_item->getQtyWeight() / $_item->getQty(), 2):''; 
    $unitweight = 0;
    if(floatval($_item->getQtyWeight()) > 0){
        $unitweight = $_item->getQtyWeight() * $_item->getCaseQty();
    } else {
        $unitweight = $_item->getQty() * $product->getWeight();
    }
    ?>
    <td class="item-qty"><?= /* @escapeNotVerified */  ($_item->getCaseQty() == 0)?$_item->getQty() * 1:$_item->getCaseQty() ?></td>
    <td class="col-weight"><?php echo (floatval($_item->getQtyWeight()) > 0)?$_item->getQtyWeight().' lbs':''; ?></td>
    <td class="col-price-lb"><?php echo $weightlb; ?></td>
    <td class="col-unit-weight"><?php echo $unitweight; ?> lbs.</td>
    <td class="item-price">
        $<?= /* @escapeNotVerified */  number_format($_item->getOrderItem()->getRowTotal(), 2) ?>
    </td>
</tr>