<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /** @var $block \Amasty\GiftCard\Block\Product\View\Type\GiftCard */ ?>
<?php $_currencyShortName = $block->getCurrencyShortName(); ?>
<?php $_product = $block->getProduct(); ?>

<?php if ($_product->isSaleable() && $block->isConfigured($_product)) : ?>
    <div class="fieldset" data-amgiftcard-js="amgiftcard-fieldset">
        <?php if ($block->isMultiAmount() || $_product->getAmGiftcardPrices()) : ?>
            <div class="field required">
                <label class="label" for="amgiftcard_amount">
                    <span><?= __('Card Value in %1', $_currencyShortName); ?></span>
                </label>
                <?php if ($block->isPredefinedAmount()) : ?>
                    <div class="control">
                        <select id="am_giftcard_amount" name="am_giftcard_amount" class="required-entry" data-amgiftcard-js="amgiftcard-amount">
                            <option value=""><?= $block->escapeHtml(__('Choose an Amount...')); ?></option>
                        <?php foreach ($block->getListAmounts() as $_amount) : ?>
                            <option data-value="<?= $block->convertPrice($_amount); ?>"
                                    value="<?= $block->convertPrice($_amount) ; ?>"
                                    data-amgiftcard-js="amgiftcard-amount-item"
                                <?php if ($block->getDefaultValue('am_giftcard_amount') == $_amount || count($block->getListAmounts()) == 1) :
                                    echo " selected";
                                endif; ?>><?= $block->getFormatPrice($_amount); ?></option>
                        <?php endforeach; ?>
                        <?php if ($_product->getAmAllowOpenAmount()) : ?>
                            <option value="custom"><?= $block->escapeHtml(__('Custom Amount')); ?></option>
                        <?php endif; ?>
                        </select>

                        <?php if ($_product->getAmAllowOpenAmount()) : ?>
                            <div class="field" id="amgiftcard_amount_custom_block"
                                 style="display: <?php if ($block->isPredefinedAmount()): ?>none<?php endif; ?>"
                                 data-amgiftcard-js="amgiftcard-custom-amount-wrapper">
                                <?php $_min = $_max = 0;
                                if ($_product->getAmOpenAmountMin() || $_product->getAmOpenAmountMax()) : ?>
                                    <?php $_min = $_product->getAmOpenAmountMin(); ?>
                                    <?php $_max = $_product->getAmOpenAmountMax(); ?>
                                    <input name="am_giftcard_amount_custom"
                                           class="validate-number-range number-range-<?= $block->round($block->convertPrice($_min)) . '-' . $block->round($block->convertPrice($_max)); ?>
                                           required-entry input-text amgiftcard-amount-custom amgiftcard-min-amount amgiftcard-max-amount"
                                           value="<?= $block->getDefaultValue('am_giftcard_amount_custom'); ?>"
                                           type="text"
                                           data-amgiftcard-js="amgiftcard-amount-custom">
                                    <div>
                                        <?php if ($_product->getAmOpenAmountMin()) : ?>
                                            <span><?= __('Minimum: %1', $block->getFormatPrice($_min));?></span>
                                        <?php endif; ?>

                                        <?php if ($_product->getAmOpenAmountMax()) : ?>
                                            <span><?= __('Maximum: %1', $block->getFormatPrice($_max));?></span>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if ($_product->getAmGiftcardType() == \Amasty\GiftCard\Model\GiftCard::TYPE_COMBINED) : ?>
            <div class="field required">
                <label for="am_giftcard_type" class="label">
                    <span><?= __('Choose card type'); ?></span>
                </label>
                <div class="input-box">
                    <select id="am_giftcard_type" name="am_giftcard_type" class="required-entry" data-amgiftcard-js="amgiftcard-type">
                        <option value=""><?= $block->escapeHtml(__('-- Please Select --')); ?></option>
                        <?php foreach ($block->getListCardTypes() as $_cardType) : ?>
                            <option value="<?= $_cardType['value']; ?>"
                                    <?php if ($block->getDefaultValue('am_giftcard_type') == $_cardType['value']) :
                                        echo " selected";
                                    endif; ?>>
                                <?= $_cardType['label']; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note amgiftcard-delivery-info">
                        <?= $block->escapeHtml(__('Please be aware that printed gift card will be sent to the shipping address you specify during checkout.')); ?>
                    </p>
                </div>
            </div>

        <?php endif; ?>

        <?php if ($_images = $block->getImages()) : ?>
            <div class="field required" data-amgiftcard-js="amgiftcard-images">
                <label for="am_giftcard_image" class="label">
                    <?= $block->escapeHtml(__('Choose card Image')); ?>
                </label>
                <div class="input-box">
                    <input type="text"
                           name="am_giftcard_image"
                           class="amgiftcard-image-input required-entry"
                           value="<?= $block->getDefaultValue('am_giftcard_image'); ?>"
                           data-amgiftcard-js="amgiftcard-image-input"/>
                    <?php foreach ($_images as $_image) : ?>
                        <img class="amgiftcard-image"
                             data-id="<?= $_image->getId() ?>"
                             src="<?= $_image->getImageUrl() ?>"
                             data-img-full-src="<?= $_image->getImageUrl(); ?>"
                             data-amgiftcard-js="amgiftcard-image"/>
                    <?php endforeach; ?>
                </div>
                <?php if ($block->getAllowUsersUploadImages()) : ?>
                    <div class="amgiftcard-userimage-container">
                        <div class="amgiftcard-image-container -hidden">
                            <div class="amgiftcard-image-wrapper">
                                <img class="amgiftcard-userimage" data-amgiftcard-js="amgiftcard-userimage"/>
                            </div>
                            <span class="amgiftcard-close" data-amgiftcard-js="amgiftcard-close"></span>
                        </div>
                        <div class="amgiftcard-browse-container">
                            <div class="amgiftcard-label-container">
                                <span class="amgiftcard-label"><?= $block->escapeHtml(__('or upload your image')) ?></span>
                                <span class="amgiftcard-note" title="<?= $block->escapeHtml(__($block->getTooltipContent())); ?>" data-amgiftcard-js="info-tooltip"></span>
                            </div>
                            <label class="amgiftcard-button" for="amgiftcard-userimage-input">
                                <span class="amgiftcard-icon -camera"></span>
                                <span class="amgiftcard-title"><?= $block->escapeHtml(__('Browse')) ?></span>
                            </label>
                            <input class="amgiftcard-image-input"
                                   type="file"
                                   id="amgiftcard-userimage-input"
                                   name="amgiftcard-userimage-input"
                                   accept=".jpg, .jpeg, .gif, .png"
                                   data-amgiftcard-js="amgiftcard-userimage-input">
                        </div>
                    </div>
                <p class="amgiftcard-error" data-amgiftcard-js="amgiftcard-userimage-error"></p>
                <?php endif; ?>
            </div>

        <?php endif; ?>
        <?php if ($block->isOptionEnable('am_giftcard_sender_name')) : ?>
            <div class="field required">
                <label for="am_giftcard_sender_name" class="label">
                    <span><?= $block->escapeHtml(__('Sender Name')); ?></span>
                </label>
                <div class="input-box">
                    <input type="text"
                           id="am_giftcard_sender_name"
                           name="am_giftcard_sender_name"
                           class="required-entry input-text"
                           value="<?= $block->getDefaultValue('am_giftcard_sender_name'); ?>"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($block->isOptionEnable('am_giftcard_sender_email')) : ?>
            <div class="field required">
                <label for="am_giftcard_sender_email" class="label">
                    <span><?= $block->escapeHtml(__('Sender Email')); ?></span>
                </label>
                <div class="input-box">
                    <input type="text"
                           id="am_giftcard_sender_email"
                           name="am_giftcard_sender_email"
                           class="validate-email required-entry input-text"
                           value="<?= $block->getDefaultValue('am_giftcard_sender_email'); ?>"/>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($_product->getAmGiftcardType() != \Amasty\GiftCard\Model\GiftCard::TYPE_PRINTED) : ?>
            <?php if ($block->isOptionEnable('am_giftcard_recipient_name')) : ?>
                <div class="field required am_giftcard_recipient_data" data-amgiftcard-js="amgiftcard-recipient-data">
                    <label for="am_giftcard_recipient_name" class="label">
                        <span><?= $block->escapeHtml(__('Recipient Name')); ?></span>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               id="am_giftcard_recipient_name"
                               name="am_giftcard_recipient_name"
                               class="required-entry input-text"
                               value="<?= $block->getDefaultValue('am_giftcard_recipient_name'); ?>"/>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field required am_giftcard_recipient_data" data-amgiftcard-js="amgiftcard-recipient-data">
                <label for="am_giftcard_recipient_email" class="label">
                    <span><?= $block->escapeHtml(__('Recipient Email')); ?></span>
                </label>
                <div class="input-box">
                    <input type="text"
                           id="am_giftcard_recipient_email"
                           name="am_giftcard_recipient_email"
                           class="validate-email required-entry input-text"
                           value="<?= $this->getDefaultValue('am_giftcard_recipient_email'); ?>"/>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable('am_giftcard_date_delivery')) : ?>
            <div class="field required">
                <label for="am_giftcard_date_delivery" class="label">
                    <span><?= $block->escapeHtml(__('Date of Certificate Delivery')); ?></span>
                </label>
                <div class="input-box">
                    <input name="am_giftcard_date_delivery"
                           id="am_giftcard_date_delivery"
                           value="<?= $block->getDefaultValue('am_giftcard_date_delivery'); ?>"
                           class="required-entry datetime-picker input-text validate-date"
                           type="text"
                           data-amgiftcard-js="amgiftcard-delivery-date">
                    <p class="note amgiftcard-delivery-info" style="display:none;" data-amgiftcard-js="amgiftcard-delivery-info">
                        <?= $block->escapeHtml(__('Please be aware that delivery date of printed certificates may be different due to post.')); ?>
                    </p>
                </div>
            </div>
            <div class="field required">
                <label for="am_giftcard_date_delivery_timezone" class="label">
                    <span><?= $block->escapeHtml(__('Select timezone')); ?></span>
                </label>
                <div class="input-box">
                    <select class="required-entry" name="am_giftcard_date_delivery_timezone" id="am_giftcard_date_delivery_timezone">
                        <option value=""></option>
                        <?php foreach ($block->getListTimezones() as $_timezone) : ?>
                            <option
                                    value="<?= $_timezone['value']; ?>"<?php if ($block->getDefaultValue('am_giftcard_date_delivery_timezone') == $_timezone['value']) {
                                echo " selected";
                            } ?>><?= $_timezone['label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($block->isOptionEnable(\Amasty\GiftCard\Model\Options::GIFT_MESSAGE)) : ?>
            <div class="field">
                <label for="am_giftcard_message" class="label">
                    <span><?= $block->escapeHtml(__('Message')); ?></span>
                </label>
                <div class="input-box">
					<textarea name="am_giftcard_message" id="am_giftcard_message" class="input-text" cols="5" rows="3"><?= $block->getDefaultValue('am_giftcard_message'); ?></textarea>
                </div>
            </div>
        <?php endif; ?>

        <div class="amgiftcard-preview">
            <button title="<?= $block->escapeHtml(__('Preview Gift Card')) ?>"
                    data-amgiftcard-js="amgiftcard-preview"
                    disabled>
                <?= $block->escapeHtml(__('Preview Gift Card')) ?>
            </button>
        </div>

        <script>
            require([
                'jquery',
                'Amasty_GiftCard/js/main',
                "mage/calendar",
                "mage/tooltip"
            ], function ($) {
                $('[data-amgiftcard-js="amgiftcard-fieldset"]').amGiftcard({
                    productId: "<?= $_product->getId(); ?>",
                    feeType: "<?= $_product->getAmGiftcardFeeType(); ?>",
                    feeValue: "<?= $_product->getAmGiftcardFeeValue(); ?>"
                });

                if ($('[data-amgiftcard-js="amgiftcard-delivery-date"]')) {
                    $('[data-amgiftcard-js="amgiftcard-delivery-date"]').calendar({
                        showTime: false,
                        minDate: new Date(),
                    });
                }

                $('[data-amgiftcard-js="info-tooltip"]').tooltip({
                    position: {
                        my: "left bottom",
                        at: "right top",
                        collision: "flipfit flipfit"

                    },
                    tooltipClass: "amgiftcard-tooltip",
                    content:
                        "<?= $block->escapeHtml(__($block->getTooltipContent())); ?>"
                });
            });
        </script>
    </div>
<?php endif; ?>
