<?php
$tree = $block->getTree();
if($tree):
?>
<div class="mp-sidebar mpcss">
    <div class="row">
        <div class="block-title col-xs-12 sidebar-categories">
            <p class="block-mp-sidebar-heading"><?php echo __('Categories') ?></p>
        </div>
        <div class="col-xs-12">
            <ul class="block-content menu-categories">
                <?php echo $block->getCategoryTreeHtml($tree) ?>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    //require(['Mageplaza_Blog/js/categorytree'], function () {});
</script>
<?php endif; ?>
