<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="copyright-left">
					<a href="https://www.facebook.com/blackwing247" target="_blank"><i class="fa fa-fw fa-facebook"></i></a>
					<a href="https://twitter.com/blackwingmeats" target="_blank"><i class="fa fa-fw fa-twitter"></i></a>
					<a href="https://www.youtube.com/" target="_blank" style="display: none;"><i class="fa fa-fw fa-youtube"></i></a>
				</div>
				<div class="copyright-right">©<?php echo date('Y'); ?> Blackwing Meats. All Rights Reserved. Web Design &amp; Development by 
					<a class="webfitters-link" href="https://webfitters.com" target="_blank">
						<img src="/pub/media/wysiwyg/footer/webfitters-logo.png" alt="">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>