<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item)?>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-weight"><?php echo (floatval($_item->getQtyWeight()) > 0)?$_item->getQtyWeight().' lbs':''; ?></td>
    <td class="col-price-lb"><?php echo (floatval($_item->getQtyWeight()) > 0)?'$'.number_format($_item->getRowTotal() / $_item->getQtyWeight(), 2):''; ?></td>
    <td class="col-price">
        <?= $block->getColumnHtml($_item, 'price') ?>
    </td>
    <td class="col-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-qty-invoice">
    <?php if ($block->canEditQty()) : ?>
        <input type="text" class="input-text admin__control-text qty-input"
               name="invoice[items][<?= /* @escapeNotVerified */ $_item->getOrderItemId() ?>]"
               value="<?= /* @escapeNotVerified */ $_item->getQty()*1 ?>"/>
    <?php else : ?>
        <?= /* @escapeNotVerified */ $_item->getQty()*1 ?>
    <?php endif; ?>
    </td>
    <td><?php echo $_item->getCaseQty(); ?></td>
    <td class="col-subtotal">
        <?= $block->getColumnHtml($_item, 'subtotal') ?>
    </td>
    <td class="col-tax"><?= /* @escapeNotVerified */ $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discount"><?= /* @escapeNotVerified */ $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?= $block->getColumnHtml($_item, 'total') ?>
    </td>
