<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $block \Amasty\GiftCard\Block\Customer\Cards */ ?>

<?php $_cards = $block->getCards() ?>
<?php if(count($_cards)): ?>
<div class="amgiftcard">
<fieldset class="fieldset">
    <legend class="legend"><span><?= $block->escapeHtml(__('Gift Codes')) ?></span></legend>
    <?php foreach($_cards as $_card): ?>
        <div class="amgiftcard-info customer-account-gift-card-item">
            <p><?= __("Code: %1", '<strong>' . $_card->getCode() . '</strong>'); ?></p>
            <p><?= __("Status: %1", '<strong>' . $_card->getStatus() . '</strong>'); ?></p>
            <p><?= __('Current Balance: %1', '<strong>' . $block->getCurrentBalance($_card->getCurrentValue()) . '</strong>'); ?></p>
            <?php if ($_card->getExpiredDate()): ?>
                <?php $_validTill = $block->getExpiredDate($_card->getExpiredDate()); ?>
            <?php else: ?>
                <?php $_validTill = $block->escapeHtml(__('unlimited')); ?>
            <?php endif; ?>
            <p><?= __('Valid till: %1', '<strong>' . $_validTill . '</strong>'); ?></p>

            <a href="<?= $block->escapeUrl($block->getUrl('amgiftcard/account/remove', array('id'=>$_card->getId()))) ?>"
               title="<?= $block->escapeHtml(__('Remove'));?>"><?= $block->escapeHtml(__('Remove'));?></a>
        </div>
    <?php endforeach; ?>
</fieldset>
</div>
<?php endif;?>
