<h3>Reports</h3>
<div style="margin-bottom: 10px;">
	<a class="action-primary" href="<?php echo $this->getUrl('reporting/reporting/sales') ?>">Gross Sales</a>
	<a class="action-primary" href="<?php echo $this->getUrl('reporting/reporting/financial') ?>">Financial Summary</a>
	<a class="action-primary" href="<?php echo $this->getUrl('reporting/reporting/inventory') ?>">Product Unfulfilled</a>
</div>